on:
  workflow_dispatch:
jobs:
  my-job:
    - name: Setup Node.js environment
      runs-on: ubuntu-latest
      uses: actions/setup-node@v4.0.2
      with:
        # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
        node-version: 18
